### ISSUE TITLE
Add birthday to contact info

### ISSUE THREAD

**Issue by timbl** [SolidOS/contacts-pane#25]

**Comment by mauritsderoover** [comment]
What exactly is meant here? It is already possible to add a birthday to a profile and it is also possible to add a friend. So I am not sure, I understand the issue?

**Comment by ewingson** [comment]
I'm also not sure. as I just see, the birthday is only displayed when in "edit-profile" mode and not displayed on the public profile. maybe this was meant...

**Comment by timea-solid** [comment]
I wonder if it is not already existing... We can ask at the weekly meeting. 
![grafik](https://user-images.githubusercontent.com/4144203/190599383-7e046c10-2270-4be7-b1db-7d5269f9db5b.png)

**Comment by TallTed** [comment]
As with other date fields, if this is not taking the user's preferences into account, it should use the unambiguous ISO numeric format, i.e., `YYYY-MM-DD`, or one of the mixed numeric+string formats that identifies the month by name, instead of any potentially ambiguous presentation including but not limited to `dd/mm/yyyy` or `mm/dd/yyyy`
